import About from '@/components/About'
import Banners from '@/components/Banners'
import Contact from '@/components/Contact'
import Raise from '@/components/Raise'
import Services from '@/components/Services'
import useWindowDimensions from '@/hooks/get-windowDimension'
import Head from 'next/head'

export default function Home() {
  const { width, height } = useWindowDimensions()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center">
        <Banners />
        <Raise />
        <Services />
        <About />
        <Contact />
      </main>
    </>
  )
}
