import Head from 'next/head'

export default function Politics() {
  return (
    <>
      <Head>
        <title>Digital Quatro - Políticas</title>
        <meta name="description" content="Generated by Digital Quatro" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center">
        <p>
          Política de Privacidade da Digital Quatro Esta Política de Privacidade descreve como a
          Digital Quatro, pessoa jurídica de direito privado, inscrita no CNPJ sob o n°
          46.948.896/0001-36, com sede na Rua Guilherme Rocha, nº 1299, Bairro Centro, município de
          Fortaleza – Ceará, CEP: 60030-141, coleta, usa, armazena, compartilha e protege
          informações pessoais dos usuários e clientes de seus serviços, nos termos da legislação
          aplicável à privacidade e proteção de dados pessoais. Coleta de informações pessoais A
          Digital Quatro coleta informações pessoais dos usuários e clientes em diversas situações,
          como quando realizam cadastro em seus serviços, realizam compras em seu site, preenchem
          formulários de contato ou participam de pesquisas. As informações coletadas incluem, mas
          não se limitam a, nome, endereço, e-mail, número de telefone e informações de pagamento.
          Uso de informações pessoais A Digital Quatro utiliza as informações pessoais coletadas
          para prestar seus serviços, processar transações, enviar informações sobre produtos e
          serviços, responder a solicitações de suporte ao cliente e melhorar a experiência do
          usuário. A empresa também poderá utilizar as informações para fins de marketing e
          publicidade direcionada, desde que obtenha o consentimento expresso do usuário.
          Compartilhamento de informações pessoais A Digital Quatro não compartilha informações
          pessoais com terceiros, exceto quando necessário para prestar seus serviços (por exemplo,
          para processar pagamentos) ou quando exigido por lei ou ordem judicial. Proteção de
          informações pessoais A Digital Quatro adota medidas de segurança física, técnica e
          administrativa para proteger as informações pessoais de seus usuários e clientes contra
          perda, uso indevido, acesso não autorizado, divulgação, alteração ou destruição. A empresa
          não pode garantir a segurança absoluta das informações transmitidas ou armazenadas
          eletronicamente. Cookies e outras tecnologias de rastreamento A Digital Quatro utiliza
          cookies e outras tecnologias de rastreamento para coletar informações sobre a interação
          dos usuários com seu site e serviços. Essas tecnologias permitem personalizar a
          experiência do usuário e oferecer anúncios personalizados com base em seu histórico de
          navegação. O usuário pode optar por não permitir cookies em seu navegador, mas isso pode
          afetar sua experiência em nosso site. Alterações nesta Política de Privacidade A Digital
          Quatro se reserva o direito de atualizar esta Política de Privacidade periodicamente, de
          acordo com as mudanças legislativas e tecnológicas aplicáveis. O usuário será notificado
          sobre as alterações significativas nesta política, mediante publicação de aviso em nosso
          site ou envio de e-mail. A empresa encoraja os usuários a revisarem esta política
          regularmente para se manterem informados sobre como protegemos as informações pessoais.
          Contato Se o usuário tiver alguma dúvida sobre esta Política de Privacidade ou sobre as
          práticas de privacidade da Digital Quatro, pode entrar em contato conosco por meio de
          nosso endereço eletrônico: contato@digitalquatro
        </p>
      </main>
    </>
  )
}
