import Head from 'next/head'

export default function Politics() {
  return (
    <>
      <Head>
        <title>Digital Quatro - Políticas</title>
        <meta name="description" content="Generated by Digital Quatro" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className="flex w-full flex-col items-start justify-center space-y-8 p-10 tracking-wider text-slate-light-1">
        <p className="text-lg font-bold">Política de Privacidade da Digital Quatro</p>
        <p className="text-base">
          Esta Política de Privacidade descreve como a Digital Quatro, pessoa jurídica de direito
          privado, inscrita no CNPJ sob o n° 46.948.896/0001-36, com sede na Rua Guilherme Rocha, nº
          1299, Bairro Centro, município de Fortaleza – Ceará, CEP: 60030-141, coleta, usa,
          armazena, compartilha e protege informações pessoais dos usuários e clientes de seus
          serviços, nos termos da legislação aplicável à privacidade e proteção de dados pessoais.
        </p>
        <p className="text-lg font-bold">Coleta de informações pessoais</p>
        <p className="text-base">
          A Digital Quatro coleta informações pessoais dos usuários e clientes em diversas
          situações, como quando realizam cadastro em seus serviços, realizam compras em seu site,
          preenchem formulários de contato ou participam de pesquisas. As informações coletadas
          incluem, mas não se limitam a, nome, endereço, e-mail, número de telefone e informações de
          pagamento.
        </p>
        <p className="text-lg font-bold">Uso de informações pessoais</p>
        <p className="text-base">
          A Digital Quatro utiliza as informações pessoais coletadas para prestar seus serviços,
          processar transações, enviar informações sobre produtos e serviços, responder a
          solicitações de suporte ao cliente e melhorar a experiência do usuário. A empresa também
          poderá utilizar as informações para fins de marketing e publicidade direcionada, desde que
          obtenha o consentimento expresso do usuário.
        </p>
        <p className="text-lg font-bold">Compartilhamento de informações pessoais</p>
        <p className="text-base">
          A Digital Quatro não compartilha informações pessoais com terceiros, exceto quando
          necessário para prestar seus serviços (por exemplo, para processar pagamentos) ou quando
          exigido por lei ou ordem judicial.
        </p>
        <p className="text-lg font-bold">Proteção de informações pessoais</p>
        <p className="text-base">
          A Digital Quatro adota medidas de segurança física, técnica e administrativa para proteger
          as informações pessoais de seus usuários e clientes contra perda, uso indevido, acesso não
          autorizado, divulgação, alteração ou destruição. A empresa não pode garantir a segurança
          absoluta das informações transmitidas ou armazenadas eletronicamente.
        </p>
        <p className="text-lg font-bold">Cookies e outras tecnologias de rastreamento</p>
        <p className="text-base">
          A Digital Quatro utiliza cookies e outras tecnologias de rastreamento para coletar
          informações sobre a interação dos usuários com seu site e serviços. Essas tecnologias
          permitem personalizar a experiência do usuário e oferecer anúncios personalizados com base
          em seucomportamento de navegação. Os usuários podem optar por desativar ou limitar o uso
          de cookies em seus navegadores, mas isso pode afetar o funcionamento do site.
        </p>
        <p className="text-lg font-bold">Alterações nesta política</p>
        <p className="text-base">
          A Digital Quatro reserva-se o direito de alterar esta Política de Privacidade a qualquer
          momento, mediante publicação da versão atualizada em seu site. É recomendável que os
          usuários revisem regularmente esta política para estar cientes de quaisquer alterações.
        </p>
        <p className="text-base">Última atualização: 17 de março de 2023.</p>
      </main>
    </>
  )
}
